config/routes.rb
Rails.application.routes.draw do
  resources :requests do
    collection do
      get 'confirm/:id'=> 'requests#confirm'
      post 'request_confirm'
    end
  end

  resources :user_profiles

  resources :otp do
    collection do
      post 'send_otp'
    end
  end

  resources :cities
  resources :localities
  resources :user_details

  devise_scope :user do
    root to: "landing#welcome"
  end
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/request.rb
class Request < ActiveRecord::Base
  enum state: [ :unverified, :open, :booked, :completed, :failed ]

  belongs_to :user
  belongs_to :city
  belongs_to :locality
  belongs_to :language
  after_create :set_status
  has_many :request_volunteers

  def broadcast_requests
    user_details = UserDetail.fetch_users_in_locality(self.locality)
    sms_requests(user_details.map(&:phone_no).compact.join(","))
  end

  def sms_requests(phone_numbers)
    base_url = "http://localhost:3000"
    link = "#{base_url}/requests/confirm/#{self.id}"
    sms_string = "Hi! #{self.user.user_detail.try(:name)} is in need of a scribe on #{self.start_time.to_date} at #{self.address}. Please click on #{link} to confirm."
    Rails.logger.info sms_string
    Sms.new(sms_string, phone_numbers).send
    #phone_numbers.each{|phone_number| Sms.send_exotel_sms(phone_number, sms_string)}
  end

  def send_confirm_message(request_volunteer)
    if request_volunteer.priority == 1
      sms_string = "Hi! Thank you for volunteering for #{self.user.user_detail.try(:name)}! We have emailed you the details!"
    else
      sms_string = "Hi! Thank you for volunteering for #{self.user.user_detail.try(:name)}! However, someone has already confirmed for this request. Don't worry, We have kept you as the next priority, and will let you know in case the the slot get's freed!"
    end
    phone_number = request_volunteer.user.user_detail.phone_no
    Sms.new(sms_string, phone_number).send
    #Sms.send_exotel_sms(phone_no, sms_string)
  end

  private

  def set_status
    self.state = Request.states[:open]
    self.save
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:request_confirm, :confirm]

  def index
    @user = current_user
    @requests = Request.where(user: current_user)
  end

  def new
    @request = Request.new
  end

  def create
    params[:request][:start_time] = DateTime.strptime(params[:request][:start_time], '%m/%d/%Y %I:%M %p')
    params[:request][:end_time] = DateTime.strptime(params[:request][:end_time], '%m/%d/%Y %I:%M %p')
    params[:request][:user_id] = current_user.id
    @request = Request.new(request_params)
    respond_to do |format|
      if @request.save
        @request.broadcast_requests
        format.html {
          redirect_to(@request, notice: 'Your request was successfully submitted.')
        }
      else
        format.html {
          render action: 'new'
        }
      end
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def confirm
    @request = Request.find(params[:id])
  end

  def request_confirm
    @request = Request.find(params[:request_id])
    valid_otp, message = Otp.verify_otp(params)
    if valid_otp
      user = UserDetail.find_by(phone_no: params[:phone_no]).user
      request_volunteer = RequestVolunteer.create(request: @request, user: user)
      priority = request_volunteer.assign_priority
      @request.send_confirm_message(request_volunteer)
      render json: {status: 200, message: "Success", priority: priority}
    else
      render json: {status: 500, message: message}
    end
  end

  private
  def request_params
    params.require(:request).permit(:exam, :subject, :address, :start_time, :end_time, :note, :user_id, :city_id, :language_id, :locality_id)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/confirm.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-3">

      <h2 class="header-thanks"> Thank you for volunteering for <%= @request.user.user_detail.name %>! </h2>
      <%= hidden_field_tag :request_id, @request.id %>
      <div class="request-confirmation-div">
        <div class="row form-group" id="mobile-div">
          <p class="instruction-text">Please enter your registered mobile number below to confirm:</p>

          <div class="col-sm-4">
            <input type="text" class="form-control" id="phone_no">
          </div>
          <div class="col-sm-2">
            <button type="button" class="btn btn-large btn-primary" onclick="confirmRequest()">Send OTP</button>
          </div>
        </div>

        <div class="row form-group" id="otp-div">
          <p class="instruction-text">Enter the OTP sent to your number to confirm:</p>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="otp">
          </div>
          <div class="col-sm-2">
            <button type="button" class="btn btn-large btn-primary" onclick="verifyOtp()">Confirm</button>
          </div>
        </div>
      </div>

      <div class="message-confirmation-div">
        <div id="confirmed">
          <h4 class="header-thanks"> Great! You are confirmed! Details will reach you shortly. </h4>
        </div>

        <div id="backup">
          <h4 class="header-thanks"> It seems like someone has confirmed to volunteer for <%= @request.user.user_detail.name %> </h4>
          <h4>We have kept you as the next priority, and will let you know in case the the slot get's freed!</h4>
        </div>

        <!--
        Thank you for volunteering. We'll get back to you with the details shortly. -->
      </div>

  </div>
</div>

app/views/requests/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="row margin-left-0">
      <div class="col-xs-2 dashboard-header"> <h2>Dashboard</h2> </div>
      <div class="col-xs-1 col-xs-offset-8 logout"> 
        <%= link_to('Profile', "/user_profiles/#{@user.id}") %> 
      </div>
      <div class="col-xs-1 logout"> 
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
      </div> 
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="panel-title pull-left">Your Requests</span>
        <span><%= button_to "New Request", new_request_path, :class => "btn btn-default pull-right", :method => :get  %></span>
        <div class="clearfix"></div>
      </div>

      <table class="table">
        <tr>
          <th>Exam</th>
          <th>Date</th>
          <th>Status</th>
          <th>City</th>
          <th>Language</th>
          <th>Action</th>
        </tr>
        <% @requests.each do |request| %>
            <tr>
              <td><%= "#{request.exam} - #{request.subject}" %></td>
              <td><%= request.start_time.strftime("%d-%m-%y (%A)") %></td>
              <td><%= request.state == 'unverified' ? 'Verification pending' : request.try(:state).try(:capitalize) %></td>
              <td><%= request.city.try(:name) %></td>
              <td><%= request.language.try(:name) %></td>
              <td><%= button_to "View", request_path(request), :class => "btn btn-default", :method => :get  %></td>
            </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>

app/views/requests/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-3">
    <%= form_for @request, url: {action: 'create'}, class: "form-horizontal" do |f| %>

        <div class="row"><h2 class="col-xs-4 col-xs-offset-3 center-text">New Request</h2></div>

        <div class="row form-group">
          <%= f.label 'Exam', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_field :exam, class: "form-control" %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Subject', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_field :subject, class: "form-control" %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'City', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :city_id, options_for_select(City.all.map{|c| [c.name, c.id]}), {}, { :class => 'form-control' } %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Locality', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :locality_id, options_for_select(Locality.all.map{|l| [l.name, l.id]}), {}, { :class => 'form-control' } %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Language', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :language_id, options_for_select(Language.all.map{|l| [l.name, l.id]}), {}, { :class => 'form-control' } %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Address', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_area :address, class: "form-control", rows: '5'  %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Start time', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_field :start_time, class: "form-control datetimepicker" %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'End time', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_field :end_time, class: "form-control datetimepicker" %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.label 'Specific Requirements', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_area :note, class: "form-control", rows: '5'  %>
          </div>
        </div>

        <div class="row form-group">
          <%= f.submit "Request", class: "col-xs-2 col-xs-offset-2 btn btn-large btn-primary" %>
          <%= link_to "Cancel", '/requests', {:class=>"col-xs-2 col-xs-offset-1 btn btn-large btn-primary"} %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('.datetimepicker').datetimepicker();
  });
</script>

app/views/requests/request_confirm.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-3">

      <h2 class="header-thanks"> Thank you for volunteering for <%= @request.user.user_detail.name %>! </h2>
      <%= hidden_field_tag :request_id, @request.id %>
      <div class="request-confirmation-div">
        <div class="row form-group" id="mobile-div">
          <p class="instruction-text">Please enter your registered mobile number below to confirm:</p>

          <div class="col-sm-4">
            <input type="text" class="form-control" id="phone_no">
          </div>
          <div class="col-sm-2">
            <button type="button" class="btn btn-large btn-primary" onclick="confirmRequest()">Send OTP</button>
          </div>
        </div>

        <div class="row form-group" id="otp-div">
          <p class="instruction-text">Enter the OTP sent to your number to confirm:</p>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="otp">
          </div>
          <div class="col-sm-2">
            <button type="button" class="btn btn-large btn-primary" onclick="verifyOtp()">Confirm</button>
          </div>
        </div>
      </div>

      <div class="message-confirmation-div">
        <div id="confirmed">
          <h4 class="header-thanks"> Great! You are confirmed! Details will reach you shortly. </h4>
        </div>

        <div id="backup">
          <h4 class="header-thanks"> It seems like someone has confirmed to volunteer for <%= @request.user.user_detail.name %> </h4>
          <h4>We have kept you as the next priority, and will let you know in case the the slot get's freed!</h4>
        </div>

        <!--
        Thank you for volunteering. We'll get back to you with the details shortly. -->
      </div>

  </div>
</div>

app/views/requests/show.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <h1>Under construction</h1>
    <%= button_to "All requests", requests_path, :class => "btn btn-default", :method => :get  %>
  </div>
</div>